export const forwardException = async (error: any) => {

}
